### ISSUE TITLE
Where do i write the cvars commands?

### ISSUE THREAD

**Issue by AndreAntG** [suppatimmo/goAFK#2]
Hi @suppatimmo, can you help me?
I'm new in configuring servers, I would like to know where to I put the cvars commands for most of the plugins in csgo.

Best regards,
André Gonçalves

**Comment by suppatimmo** [comment]
Hello @AndreAntG. You should check csgo/cfg/server.cfg ; csgo/cfg/sourcemod ; csgo/addons/sourcemod/configs/ directories.
Best regards :)
